### ISSUE TITLE
Nvidia's DKMS will not install on 5.12

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/linux-tkg#205]
I wasn't sure whether this should go on the nvidia-tkg repo or here, but I decided to put it here, since dkms with nvidia-tkg works perfectly fine on every other kernel I have installed (including multiple linux-tkg ones). 

While trying to install the vulkan-dev dkms package, I get: 
```
==> dkms install --no-depmod -m nvidia -v 455.50.10 -k 5.12.0-rc3-139-tkg-cfs
Error! Bad return status for module build on kernel: 5.12.0-rc3-139-tkg-cfs (x86_64)
Consult /var/lib/dkms/nvidia/455.50.10/build/make.log for more information.
==> Warning, `dkms install --no-depmod -m nvidia -v 455.50.10 -k 5.12.0-rc3-139-tkg-cfs' returned 10
```

The only error-like messages I can see in the make.log logfile are: 

```
  CC [M]  /var/lib/dkms/nvidia/455.50.10/build/nvidia/os-mlock.o
/var/lib/dkms/nvidia/455.50.10/build/nvidia/nv-mmap.c: In function ‘nv_encode_caching’:
/var/lib/dkms/nvidia/455.50.10/build/nvidia/nv-mmap.c:334:16: warning: this statement may fall through [-Wimplicit-fallthrough=]
  334 |             if (NV_ALLOW_CACHING(memory_type))
      |                ^
/var/lib/dkms/nvidia/455.50.10/build/nvidia/nv-mmap.c:336:9: note: here
  336 |         default:
      |         ^~~~~~~
```

And then: 

```
  LD [M]  /var/lib/dkms/nvidia/455.50.10/build/nvidia-uvm.o
/var/lib/dkms/nvidia/455.50.10/build/nvidia-drm/nvidia-drm-gem-user-memory.c: In function ‘nv_drm_gem_user_memory_import_sg_table’:
/var/lib/dkms/nvidia/455.50.10/build/nvidia-drm/nvidia-drm-gem-user-memory.c:211:9: error: implicit declaration of function ‘drm_prime_sg_to_page_addr_arrays’; did you mean ‘drm_prime_sg_to_dma_addr_array’? [-Werror=implicit-function-declaration]
  211 |     if (drm_prime_sg_to_page_addr_arrays(sgt, pages, NULL, pages_count) < 0) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         drm_prime_sg_to_dma_addr_array
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:271: /var/lib/dkms/nvidia/455.50.10/build/nvidia-drm/nvidia-drm-gem-user-memory.o] Error 1
make[1]: *** [Makefile:1851: /var/lib/dkms/nvidia/455.50.10/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.12.0-rc3-139-tkg-cfs/build'
make: *** [Makefile:81: modules] Error 2
```

Works fine on 5.11, has always worked on 5.10, 5.9, and 5.8 as well. 

If this should be moved to nvidia-tkg, let me know. 

Oh I will also say that trying the latest feature branch as opposed to the vulkan dev branch (so 460 instead of 455.50) gives me the same result.

**Comment by ptr1337** [comment]
Which compiler did you used for the 5.12 kernel ? When ive compiled a kernel with llvm-rc i got also a error when installing dkms.
Which mostly reffering to this issue: https://github.com/Tk-Glitch/PKGBUILDS/issues/334

But probally the the newest nvidia driver will work with 5.12. 
Take a watch here.
https://github.com/Frogging-Family/nvidia-all/commit/9b7d9b0c0d81626204800a6761e52130211c9e6e

**Comment by gardotd426** [comment]
I'm compiling on the same machine I always use, and using GCC, so that's not it. 

Yeah I saw they released a new driver today, I planned on checking it out, we'll see how it goes.

**Comment by gardotd426** [comment]
Looks like it successfully installed using 460.67 on 5.12-rc3-tkg-cfs, I still need to reboot and make sure, but if everything works I'll go ahead and close. 

Also Etienne I like the new kernel recommendations on nvidia-tkg, that's a nice touch.

**Comment by gardotd426** [comment]
Looks like everything is booted up okay with the 5.12 kernel using 460.67. I'm assuming Vulkan dev driver will be fixed in the next update as well, so yeah I'll go ahead and close, it looks like this was an Nvidia issue.
