### ISSUE TITLE
Error building linux 5.16.13

### ISSUE THREAD

**Issue by robson-66** [Frogging-Family/linux-tkg#451]
```
kernel/sched/alt_core.c:2985:6: error: conflicting types for ‘sched_post_fork’; have ‘void(struct task_struct *, struct kernel_clone_args *)’
 2985 | void sched_post_fork(struct task_struct *p, struct kernel_clone_args *kargs)
      |      ^~~~~~~~~~~~~~~
In file included from ./include/linux/sched/signal.h:9,
                 from ./include/linux/rcuwait.h:6,
                 from ./include/linux/percpu-rwsem.h:7,
                 from ./include/linux/fs.h:33,
                 from ./include/linux/huge_mm.h:8,
                 from ./include/linux/mm.h:716,
                 from ./include/linux/ring_buffer.h:5,
                 from ./include/linux/trace_events.h:6,
                 from ./include/trace/trace_events.h:21,
                 from ./include/trace/define_trace.h:102,
                 from ./include/trace/events/sched.h:738,
                 from kernel/sched/alt_core.c:15:
./include/linux/sched/task.h:58:13: note: previous declaration of ‘sched_post_fork’ with type ‘void(struct task_struct *)’
   58 | extern void sched_post_fork(struct task_struct *p);
      |             ^~~~~~~~~~~~~~~
  CC      kernel/power/main.o
make[2]: *** [scripts/Makefile.build:287: kernel/sched/alt_core.o] Error 1
make[1]: *** [scripts/Makefile.build:549: kernel/sched] Error 2
make[1]: *** Waiting for incomplete tasks....
```

**Comment by jhu54** [comment]
Have the same issue, 5.17-rc7 compiles just fine

**Comment by talzahr** [comment]
Same for me as well. Using a custom config but has worked fine on all other 5.16 builds. I then tried it with the default config and no dice. Also tried with a few different settings in makepkg.conf as well as a reboot after full update.

**Comment by AdelKS** [comment]
is this a PDS build ?

**Comment by robson-66** [comment]
`_cpusched="bmq"`

**Comment by AdelKS** [comment]
Wait or build with CFS till the Project C patch gets updated.

**Comment by robson-66** [comment]
> Wait or build with CFS till the Project C patch gets updated.

I will wait.
